pid_controller:
  ros__parameters:
    'kp_linear': 0.3
    'ki_linear': 0.0
    'kd_linear': 0.0
    'kp_angular': 0.65
    'ki_angular': 0.0
    'kd_angular': 0.01

gps_navigate:
  ros__parameters:
    waypoints: [
      (40.748817, -73.985428),  # First waypoint (set to 0,0)
      (40.748900, -73.986200),
      (40.749000, -73.987000),
    ]