pid_controller:
  ros__parameters:
    'kp_linear': 0.3
    'ki_linear': 0.0
    'kd_linear': 0.0
    'kp_angular': 0.65
    'ki_angular': 0.0
    'kd_angular': 0.01

gps_navigate:
  ros__parameters:
    waypoints: [
      "1.0,1.0",
      "2.0,2.0"
    ]