pid_controller:
  ros__parameters:
    'kp_linear': 0.3
    'ki_linear': 0.0
    'kd_linear': 0.0
    'kp_angular': 0.65
    'ki_angular': 0.0
    'kd_angular': 0.01

gps_navigate:
  ros__parameters:
    waypoints: [
      "42.876379,-77.007822",
      "42.876373,-77.007596",
      "42.876278,-77.007588",
    ]
